version: '3.8'

services:
  backend:
    build:
      context: .
    image: gestao-escolar-backend
    container_name: gestao-escolar-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8080:8080"
