version: '3.8'

services:
  backend:
    build:
      context: .
    image: gestao-escolar-backend
    container_name: gestao-escolar-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
