version: '3.8'

services:
  backend:
    build:
      context: .
    image: gestao-escolar-backend
    container_name: gestao-escolar-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${SPRING_DATASOURCE_URL}
      - DB_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - DB_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - jwt.secret=${JWT_SECRET}
      - jwt.expiration=${JWT_EXPIRATION-MS}
